server:
  port: 9081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://localhost/keycloak/auth/realms/iot
          jwk-set-uri: http://localhost/keycloak/auth/realms/iot/protocol/openid-connect/certs

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      forwarded: true
      x-forwarded:
        enable: true
        forEnabled: true
        protoEnabled: true
      routes:
        - id: tsa
          uri: http://localhost:9090
          predicates:
            - Path=/api/tsa/**
          filters:
            - RewritePath=/api/tsa/(?<segment>.*), /$\{segment}
            - TenantId=
            - UserId=
        - id: asset
          uri: http://localhost:9091
          predicates:
            - Path=/api/asset/**
          filters:
            - RewritePath=/api/asset/(?<segment>.*), /$\{segment}
            - TenantId=
            - UserId=
        - id: stream
          uri: http://localhost:9092
          predicates:
            - Path=/api/stream/**
          filters:
            - RewritePath=/api/stream/(?<segment>.*), /$\{segment}
            - TenantId=
            - UserId=
---
spring:
  profiles: docker-compose
  security:
    oauth2:
      resourceserver:
        jwt:
          #issuer-uri: http://nginx-service/keycloak/auth/realms/iot
          jwk-set-uri: http://nginx-service/keycloak/auth/realms/iot/protocol/openid-connect/certs
  cloud:
    gateway:
      globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders: "*"
      forwarded: true
      x-forwarded:
        enable: true
        forEnabled: true
        protoEnabled: true
      routes:
        - id: tsa
          uri: http://tsa-service:9090
          predicates:
            - Path=/api/tsa/**
          filters:
            - RewritePath=/api/tsa/(?<segment>.*), /$\{segment}
            - TenantId=
            - UserId=
        - id: asset
          uri: http://asset-service:9091
          predicates:
            - Path=/api/asset/**
          filters:
            - RewritePath=/api/asset/(?<segment>.*), /$\{segment}
            - TenantId=
            - UserId=
        - id: stream
          uri: http://stream-service:9092
          predicates:
            - Path=/api/stream/**
          filters:
            - RewritePath=/api/stream/(?<segment>.*), /$\{segment}
            - TenantId=
            - UserId=